package simply.simply_study.controller;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;
import simply.simply_study.repository.*;

import static org.hamcrest.Matchers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
public class UserControllerTest {

        private MockMvc mockMvc;

        @Autowired
        private WebApplicationContext webApplicationContext;

        @Autowired
        private UserRepository userRepository;

        @Autowired
        private BookingSessionRepository bookingSessionRepository;

        @Autowired
        private BookingRepository bookingRepository;

        @Autowired
        private SessionRepository sessionRepository;

        @Autowired
        private OfferingRepository offeringRepository;

        @Autowired
        private CourseRepository courseRepository;

        @BeforeEach
        public void setUp() {
                mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext).build();
                bookingSessionRepository.deleteAll();
                bookingRepository.deleteAll();
                sessionRepository.deleteAll();
                offeringRepository.deleteAll();
                courseRepository.deleteAll();
                userRepository.deleteAll();
        }

        @Test
        public void testCreateUserWithAutoGeneratedId() throws Exception {
                String requestJson = "{" +
                                "\"id\":\"\"," +
                                "\"name\":\"John Doe\"," +
                                "\"email\":\"john.doe@example.com\"," +
                                "\"role\":\"TEACHER\"," +
                                "\"timezone\":\"UTC\"" +
                                "}";

                mockMvc.perform(post("/api/users")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                                .andExpect(status().isCreated())
                                .andExpect(jsonPath("$.success", is(true)))
                                .andExpect(jsonPath("$.message", is("User registered successfully")))
                                .andExpect(jsonPath("$.data.id", notNullValue()))
                                .andExpect(jsonPath("$.data.id", not(emptyString())))
                                .andExpect(jsonPath("$.data.name", is("John Doe")))
                                .andExpect(jsonPath("$.data.email", is("john.doe@example.com")));
        }

        @Test
        public void testCreateUserWithDuplicateEmailThrowsConflict() throws Exception {
                // Register first user
                String firstRequestJson = "{" +
                                "\"id\":\"custom-id-1\"," +
                                "\"name\":\"John Doe\"," +
                                "\"email\":\"duplicate@example.com\"," +
                                "\"role\":\"TEACHER\"," +
                                "\"timezone\":\"UTC\"" +
                                "}";

                mockMvc.perform(post("/api/users")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(firstRequestJson))
                                .andExpect(status().isCreated());

                // Attempt duplicate registration
                String duplicateRequestJson = "{" +
                                "\"id\":\"\"," +
                                "\"name\":\"Jane Doe\"," +
                                "\"email\":\"duplicate@example.com\"," +
                                "\"role\":\"PARENT\"," +
                                "\"timezone\":\"Asia/Kolkata\"" +
                                "}";

                mockMvc.perform(post("/api/users")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(duplicateRequestJson))
                                .andExpect(status().isConflict())
                                .andExpect(jsonPath("$.success", is(false)))
                                .andExpect(jsonPath("$.message", is("Email 'duplicate@example.com' is already registered")))
                                .andExpect(jsonPath("$.data", nullValue()))
                                .andExpect(jsonPath("$.errors").doesNotExist())
                                .andExpect(jsonPath("$.timestamp", notNullValue()))
                                .andExpect(jsonPath("$.path", is("/api/users")))
                                .andExpect(jsonPath("$.status", is(409)))
                                .andExpect(jsonPath("$.error", is("Conflict")));
        }

        @Test
        public void testGetUserRoleWithQueryParam() throws Exception {
                // Register a teacher first
                String requestJson = "{" +
                                "\"id\":\"teacher-role-id\"," +
                                "\"name\":\"Teacher Test\"," +
                                "\"email\":\"teacher.test@example.com\"," +
                                "\"role\":\"TEACHER\"," +
                                "\"timezone\":\"UTC\"" +
                                "}";

                mockMvc.perform(post("/api/users")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(requestJson))
                                .andExpect(status().isCreated());

                // Fetch role via /api/users/role?id=teacher-role-id
                mockMvc.perform(get("/api/users/role")
                                .param("id", "teacher-role-id"))
                                .andExpect(status().isOk())
                                .andExpect(jsonPath("$.success", is(true)))
                                .andExpect(jsonPath("$.message", is("User role retrieved successfully")))
                                .andExpect(jsonPath("$.data.id", is("teacher-role-id")))
                                .andExpect(jsonPath("$.data.role", is("TEACHER")))
                                .andExpect(jsonPath("$.data.isTeacher", is(true)))
                                .andExpect(jsonPath("$.data.isParent", is(false)));

                // Fetch role via /api/users/role?userId=teacher-role-id
                mockMvc.perform(get("/api/users/role")
                                .param("userId", "teacher-role-id"))
                                .andExpect(status().isOk())
                                .andExpect(jsonPath("$.success", is(true)))
                                .andExpect(jsonPath("$.data.id", is("teacher-role-id")));
        }

        @Test
        public void testGetUsersFilteredByRoleCaseInsensitive() throws Exception {
                // Register a parent
                String parentJson = "{" +
                                "\"id\":\"parent-filter-id\"," +
                                "\"name\":\"Parent Test\"," +
                                "\"email\":\"parent.test@example.com\"," +
                                "\"role\":\"PARENT\"," +
                                "\"timezone\":\"UTC\"" +
                                "}";
                mockMvc.perform(post("/api/users")
                                .contentType(MediaType.APPLICATION_JSON)
                                .content(parentJson))
                                .andExpect(status().isCreated());

                // Filter by role=parent (lowercase)
                mockMvc.perform(get("/api/users")
                                .param("role", "parent"))
                                .andExpect(status().isOk())
                                .andExpect(jsonPath("$.success", is(true)))
                                .andExpect(jsonPath("$.data", hasSize(1)))
                                .andExpect(jsonPath("$.data[0].id", is("parent-filter-id")));

                // Filter by role=TEACHER (uppercase)
                mockMvc.perform(get("/api/users")
                                .param("role", "TEACHER"))
                                .andExpect(status().isOk())
                                .andExpect(jsonPath("$.success", is(true)))
                                .andExpect(jsonPath("$.data", hasSize(0)));
        }
}
